sudo: false
language: scala

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "Avasil/monix-circe" && sbt ++$TRAVIS_SCALA_VERSION publish
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "Avasil/monix-circe" && test $TRAVIS_SCALA_VERSION == "2.12.8"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
